# Generated by Django 4.2.8 on 2024-01-23 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_bookcontributor_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontributor',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.contributor'),
        ),
    ]
